
version: "3"
services:
  orb_slam3_22_humble:
    image: orb-slam3-humble:22.04
    container_name: orb-slam
    volumes:
      #full dev
      - /dev:/dev:rw
      - /run/udev:/run/udev:ro
      - /opt/vc:/opt/vc:ro
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #ros-workspaces
      - ./container_root/:/root/
      - ./ros_env_vars.sh:/root/ros_env_vars.sh
      - ./orb_slam3_ros2_wrapper/:/root/colcon_ws/src/orb_slam3_ros2_wrapper/
      - ./orb_slam3_map_generator/:/root/colcon_ws/src/orb_slam3_map_generator/
      - ./slam_msgs/:/root/colcon_ws/src/slam_msgs/
      - ./ORB_SLAM3/:/home/orb/ORB_SLAM3/
    privileged: true
    restart: always
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    group_add:
      - video
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/media0:/dev/media0
      - /dev/media3:/dev/media3
      - /dev/video0:/dev/video0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - DISPLAY
      - LIBCAMERA_DRIVER=raspberry_pi
      - LD_LIBRARY_PATH=/opt/vc/lib
      - LIBCAMERA_LOG_LEVELS=*:ERROR
      - ROS_DOMAIN_ID=0
    entrypoint: /bin/bash
